sudo: false
language: node_js
os:
  - osx
  - linux
  - windows
node_js:
  - '8'
  - '10'
  - '12'
  - 'node'

install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi
  - yarn

script:
  - yarn build
  - yarn test:e2e

cache:
  yarn: true
  directories:
    - .vscode-test
